### ISSUE TITLE
Coq formalizations ?

### ISSUE THREAD

**Issue by spitters** [formalabstracts/formalabstracts#14]
@andrejbauer Challenged us to formalize our own papers.
Our recent paper [Modalities in Homotopy type theory](https://arxiv.org/abs/1706.07526) with @mikeshulman and @egbertrijke comes with a quite substantial formalization in https://github.com/HoTT/HoTT 
This is **not** lean3. Is there a way this can/should be included?

Sorry, to go off on a tangent when the project is only getting started. However, it might provide a good concrete discussion topic.

**Comment by digama0** [comment]
Obviously if the result is already formalized, the need for an fabstract is considerably lessened. Nevertheless, it still seems possible to be able to state the main result as a lean axiom in the same way as everything else. I don't know the answer to whether we should transpose the HoTT library here just for the fabstract - it seems like a bad idea, even if it were all in Lean. I think this can be made more precise in the following way: The fabstracts project is not really designed for full formalizations. If you want to completely formalize a fabstract, you should do so in a separate project, and link it from here, where only the statements of important theorems should be given.

As pertains specifically to your paper, it is my view that HoTT metatheory papers should be formalized in Lean as *internal* results, i.e. via deep embedding, rather than directly as syntactic extensions to lean as most HoTT formalizations do. This matches the level of the discussion in the paper itself (which generally reason explicitly about the models and their properties and gadgets), and additionally allows it to coexist with Lean 3, which is not HoTT-friendly at the syntax level (specifically, UIP is built in, so an axiomatized HoTT extension would be inconsistent without a lot of care).

**Comment by andrejbauer** [comment]
Of course, fabstracts is the wrong place to deal with interaction between Coq and Lean.

But of course there should be a way to publish a fabstract about a formalization! It would in fact be crazy to say that fabstracts may only refer to non-formalized mathematics. So I would suggest that you simply follow the same pattern, but for the `doi` (which ought to be called `uri`) you provide a link to the repo.

**Comment by spitters** [comment]
Let's simplify things. How would I make an fabstract of a HoTT result, even if it was stated in lean.
@fpvandoorn @rlewis1988 is there a way to make to support fabstracts in to versions of lean?
I guess this would be a matter of specifying which version of lean to use in the makefile.

**Comment by fpvandoorn** [comment]
There's currently no way to have both `lean` files compiling with the newest version of Lean and `hlean` files compiling with the Lean 2 HoTT library. 

The more general question is how to formulate results in logics which are incompatible with the standard mode of Lean. As Mario said, one way is to have a deep embedding of the logic, although that will be a lot of work.

**Comment by robertylewis** [comment]
@spitters There's definitely no infrastructure for that right now. As I said in another thread, versioning issues aren't even settled within Lean 3, let alone between Lean 2 and Lean 3. 

My mental picture of this project is that it isn't really designed for foundational results. If the theorem you're turning into an fabstract depends on the choice of foundations enough that the choice of Lean versions matters, then as Mario points out, a deep embedding seems appropriate, since the "content" of the theorem must involve fairly specific type-theoretic details that need to be spelled out. The same usually can't be said for results in, say, number theory.

**Comment by andrejbauer** [comment]
May we close this with the phrase *"just do it"*?

**Comment by andrejbauer** [comment]
Just do something, anything.
