### ISSUE TITLE
Does Thomas Hales exist?

### ISSUE THREAD

**Issue by andrejbauer** [formalabstracts/formalabstracts#23]
Has anyone (by which I mean @picrin) invited Thomas Hales to this repository? I can't find him on GitHub, unless he is @flyspeck or some such. It's imperative that we bring people in early on, especially the ideological leader and an experienced formalizer such as professor Hales.

**Comment by digama0** [comment]
Based on his git history, I'm pretty sure @flyspeck is Tom Hales. (Note that that is a user account, not an organization account.)

**Comment by robertylewis** [comment]
Indeed, @flyspeck is Tom. He said earlier today that he plans to change that and join the discussion here soon.

**Comment by andrejbauer** [comment]
Very well then, Tom can prove his existence by closing this issue.

**Comment by picrin** [comment]
I did, from the very beginning (I've invited him to be the owner, and I
checked with him that he uses the flyspeck login), but he hasn't
accepted yet. He's on the mailing list though (I've made him an owner
there too).

Adam

**Comment by thalesant** [comment]
Thanks for being patient.  I have been arguing for my nonexistence for many years, but this seems to be the first time others have supported the claim.  Yes, I'm here. I have a new identity "thalesant" that I will use instead of "flyspeck."  The formal abstract for the Kepler conjecture is now uploaded.
