### ISSUE TITLE
Should formal abstracts give complete specifications?

### ISSUE THREAD

**Issue by thalesant** [formalabstracts/formalabstracts#25]
The issue is how far formal abstracts should go in giving specifications of the theorem.

My strong preference is for everything to be completely specified all the way to the logic, rather than leaving undefined constants.  For example, the number pi appears in the statement of the Kepler conjecture.  Is it enough to declare a real constant pi?  I would say no.  There should also be a specification of the number pi (as I have done in real_axiom.lean).  

Of course, we are now in an experimental stage of the project, and the libraries are not there.  But eventually, I hope that specification libraries for analysis, algebra, geometry, and so forth are created so that everything is eventually grounded.

I would not insist on unique existence for specifications.  A useful Lean idiom might be something like

specification pi : \R := some (\exist pi, spec pi)

which would create a constant pi of type real \R, and then create an axiom 'spec pi' specifying it.  By using this construction, dangling constants would be discouraged.

**Comment by andrejbauer** [comment]
We should not insist on complete specification, or else the project will be dead before it started.

I think at least in the foreseeable future it is completely infeasable to require a complete specification. For instance, the one paper I've got in there would require me to first define: categories, toposes, partial combinatory algebras, realizability toposes, ordinal numbers, infinite-time Turing machines, the PCA of infinite-time Turing machines. I would never be done, and I would never contribute.

We have now the `unfinished` keyword which lets us track precisely what is unfinished with `#print axioms`. This allows us to make gradual progress, rather than play an all-or-nothing game.

I also have very very serious doubts that it is actually possible to fit all of fabstracts into a single monolithic hierarchy of mathematical concepts. Almost anywhere we look, people use slightly different definitions. Is L₂([0,1]) a quotient of square-integrable measurable functions or the metric completion of simple functions? Is a graph given by a set of vertices and a set of edges, or a set of vertices and a relation on edges? Are the reals given as Dedekind cuts (one sided or two sided?), or the Cauchy completion of rationals. I think we **should not** try to resolve these questions. What we should do is **collect** formalizations of real mathematics, however incomplete they may be. The question on how to fit them all together is difficult, both from a mathematical and sociological point of view. We should not underestimate it.

**Comment by andrejbauer** [comment]
By the way, I am not saying we should give up on complete specification, just that we should treat completeness of specification as a serious issue and make sure that people can contribute without providing complete specification.

**Comment by digama0** [comment]
I agree with Andrej. We *should* be providing complete specifications, in the sense that not doing so should be viewed as unfinished work, but we should encourage such unfinished work since it is still much better than nothing. Essentially, this project is practicing a "top-down" formalization style, rather than the bottom-up style which is usually done in formalizations.

I would eventually like a definition of `pi`, but if it is defined all the way to the bottom then it should be done in the Lean library instead, or migrated afterwards. (A library for real numbers is already under construction.)

**Comment by thalesant** [comment]
I hope that we can at least make it an aim to give complete specification, without insisting that contributors must supply their own definitions.  I hope that we can get some people directly involved in building formal dictionaries of definitions.  

Admittedly, people use slightly different definitions and the variants should be noted.  Where there are easy implications and equivalences relating definitions, these relationships can be stated as axioms.  There are also coherent bodies of definitions that we can draw upon, such as Bourbaki.  I hope that we eventually get to the point where those supplying abstracts can simply link to the system of definitions that they use.

**Comment by andrejbauer** [comment]
I agree that the system should encourage people to give as complete a specification as possible, but they should not be deterred from contributing because their specification is incomplete.

Regarding "easy equivalences", there is a trap there. Suppose you use definition of reals `R1` and I use definition of reals `R2`, and let `E` be the equivalence of `R1` and `R2`. You prove theorem `T1` about `R1`. How do I now use `E` to transport `T1` so that I obtain the corresponding theorem `T2` about `R2`? This is what the univalence axiom is about.

**Comment by thalesant** [comment]
I could sense that univalence was coming....

**Comment by digama0** [comment]
The `transfer` tactic is intended for exactly that in Lean 3.

**Comment by andrejbauer** [comment]
@digama0 Can you say a bit more? How is that supposed to work for dependent types, where it gets tricky.

**Comment by fpvandoorn** [comment]
> I also have very very serious doubts that it is actually possible to fit all of fabstracts into a single monolithic hierarchy of mathematical concepts. 

I think most mathematicians don't care about which definition you give of something if they are classically equivalent. In all those cases (such as Dedekind cuts vs Cauchy completion) we can just choose one definition and most abstracts can use that (of course, if we have a paper which proves the equivalence then they will have to define one variant themselves). I don't think you will find mathematicians doing Lie groups / functional analysis / measure theory which will say "we formulated our paper using the Cauchy reals, not with the Dedekind reals".

Of course, for graphs where there is a set of edges between two nodes vs a relation of nodes, those are two different concepts, and we should have both. In this case, one of them is more general than the other one, so we can formulate every definition which works for the more general definition of graph in terms of that definition.

For other definitions there is not a most general definition (like the definition of "integral"). In this case I think we still should have a preferred definition, which all authors who don't care about the distinction should use.

**Comment by digama0** [comment]
@andrejbauer Sorry, I don't actually know too much about the tactic and how to use it, and documentation is sparse (read: nonexistent). I suggest you first find an actual use-case, then ask @johoelzl about it. Until then, just know that the functionality exists in principle and can be automated.

**Comment by andrejbauer** [comment]
@fpvandoorn I have a problem, namely that I do not believe that it is in fact the case that it doesn't matter which definitions are used. As we know from software development, various software components typically do not quite fit together and there is *significant* work in developing plumbing that makes them fit. I suspect that the situation with mathematics is similar, except that mathematicians live in denial regarding the amount of plumbing that is needed to make pieces of mathematics fit togethe. *All* I am saying is (a) do not pretend that all is rosy, and (b) do not assume responsibility for creating the plumbing, because that is going to be a really difficult problem.

**Comment by andrejbauer** [comment]
On a purely sociological level, I think it would be wise to avoid creating a centrally controlled monolithic system. As I already said, everyone who's ever done that never got very far with formalization. Perhaps it's time to try something different.

**Comment by fpvandoorn** [comment]
Ok, we can try that. I am very worried about the prospect of merging things later though, once two libraries are in place with slightly different definitions which can be merged in principle, merging them is much more painful than having them use the same definitions in the first place.

**Comment by andrejbauer** [comment]
Could we think of a solution along MathClasses (I summon @spitters), where everything in folklore is a math class? This way we'd never commit to a particular implementation of any object, so the question of "correct construction" would not arise.

I just feel that since Real Mathematicians never actually choose a particular version of reals in their papers, fabstracts should reflect this fact. If we start making choices that were not made by the authors of the papers, we might get into a lot of trouble (politically and mathematically speaking). Would anyone like to be told by Stephen Cook (who is of course a very nice person), for instance, that they used the wrong definition of Turing machine when they fabstracted his paper?

**Comment by digama0** [comment]
> Would anyone like to be told by Stephen Cook, for instance, that they used the wrong definition of Turing machine when they fabstracted his paper?

Very subtle. :) I think that the approach you sketch, of specifying only interfaces for a mathematical construct, does not differ substantially from Tom's original suggestion of a constant + specification, except there is less bookkeeping with that approach. To me there is essentially no difference between "we formalize a notion X parameterized over any object O satisfying certain properties" and "we assume the existence of an object O satisfying certain properties and use it to formalize notion X". The difference only arises if we need to explicitly need to consider different such objects O, in which case the properties are insufficient in any case (for that paper).

You have warned against over-engineering in other PRs; to me this is over-engineering.

**Comment by spitters** [comment]
@andrejbauer Yes, for definitions where we have a number of reasonable candidates, type classes seem like a good solution. Lean also has an implementation of transfer(parametricity) which may be another solution.

**Comment by andrejbauer** [comment]
If we rely on type classes then we can instantiate them *in many ways*, but constants can only be replaced with a single definition, if I understand correctly.

**Comment by robertylewis** [comment]
> Could we think of a solution along MathClasses

In the discussion on an earlier PR (the P=NP one, I think) I suggested that we try to agree on the interfaces for definitions, instead of the implementations. Type classes are a way to achieve this. @thalesant 's definition of the reals, for instance, declares them as a constant which implements the `linear_ordered_field` type class. It would be easy to extend this to a `complete_linear_ordered_field` class, and to use this class instead of the constant `real`.

This would change what the theorem statements look like, and not for the better. The Kepler conjecture would become
```lean
unfinished Kepler_conjecture {ℝ : Type} [complete_linear_ordered_field ℝ] :
(∀ (V : set (vector ℝ 3)), packing V → ...
```
This makes it explicit that the result is parametric over implementations of the reals, but what mathematician actually thinks like that? There are some workarounds. You can include the variable ℝ and the type class hypothesis once at the top of the file, for instance. We can create another type class that bundles more properties of ℝ, and give it a more descriptive name. 

Since making the suggestion, I've started to wonder how broadly it applies. What is the type class definition of a Turing machine, for instance? The reals are a simple case (for a classical mathematician, at least), but in the Turing machine case, I think people care about a much broader range of abstractions of computation. Agreeing on "the" spec for Turing machines would be easier than agreeing on "the" implementation, but still not trivial. There's a spectrum of cases between the reals and Turing machines, and I don't have any sense of where we'd start to have trouble.
