### ISSUE TITLE
Compilation issues in meta_data.lean

### ISSUE THREAD

**Issue by picrin** [formalabstracts/formalabstracts#37]
I'm using `Lean (version 3.2.0, commit 9a386ae188e8, Release)`. When I try to compile meta_data.lean with `lean --make meta_data.lean` I'm getting the following error:

```
error: unknown attribute [user_command]
error: unknown identifier 'decl_meta_info'
warning: declaration 'unfinished_cmd' uses sorry
```

I can get rid of by commenting out this piece of code from meta_data.lean

```
135 --@[user_command]
136 --meta def unfinished_cmd (meta_info : decl_meta_info) (_ : parse $ tk "unfinished") : lean.parser unit :=
137 --do nm ← ident,
138 --   tk ":",
139 --   tp ← lean.parser.pexpr 0,
140 --   tk ":=",
141 --   struct ← lean.parser.pexpr,
142 --   add_unfinished nm tp struct
```

I'd go ahead and do it, but I don't understand this sort of metaprogramming in lean (and what's being achieved with this piece of code), so I'd like a second opinion here.

This is a blocker of #36, as compilation of every module depends on meta_data, which doesn't compile as of yet.

**Comment by digama0** [comment]
You are using the release version. Until 3.3.0 is released, you will have to build this repo using the git version, which supports user commands.

PS: Any chance I could get collaborator status? Then I could close this issue myself.

**Comment by picrin** [comment]
Does it mean I have to compile the source code from git repo? I don't think that will be desirable from the point of view of Continuous Integration (#36). If we are to download lean independently on every pull request, it's maybe easier to just grab the binary.

**Comment by favonia** [comment]
@picrin We can avoid some or most recompilation by exploiting various cache mechanisms so that we only fully build Lean the first time. We can even fix the git commit hash directly in the Travis configuration to avoid 99% of the recompilation. Or, we can isolate the Lean building (into a separate Docker build file maybe) and upload the image on our own. Or we can do some other things. In any way, compilation from source is not that expensive.

For example, the [HoTT-Agda](https://github.com/HoTT/HoTT-Agda/blob/master/.travis.yml) compiles Agda by itself, but then uses cache to keep the binary Agda execute file across different builds. Therefore 99% of the time it only takes a few seconds to have a running Agda. Hope this helps.
